### ISSUE TITLE
All "my.id" are blocked.

### ISSUE THREAD

**Issue by bayuah** [nfacha/temporary-email-list#3]
It seems all domain with suffix `my.id` as flagged as "list.txt" and "list.json" say. That domain for personal use in Indonesia.

Why said domain there and is this possible to remove it as it will trigger false positive?

Thank you.

**Further reading:** https://en.wikipedia.org/wiki/.id

**Comment by nfacha** [comment]
I have added the domain to the whitelist on the unfiltered branch, and will merge to master once i run the filter script to cleanup old domains

**Comment by bayuah** [comment]
@nfacha: Thank you.

**Comment by nfacha** [comment]
> @nfacha: Thank you.

This is now merged into master
